config/routes.rb
MyCUplanner::Application.routes.draw do
  resources :events

  

  resources :courses do
    collection do
      post 'selected_courses'
      put 'update_multiple'
      post 'delete_multiple'
      post 'send_to_calendar'
      post 'send_to_index'
    end
  end

  match '/select_courses_taken', to: 'courses#select_courses_taken', via:'get'

  root :to => 'users#home'
  match '/about',   to: 'dynamic_pages#about',   via: 'get'
  match '/contact', to: 'dynamic_pages#contact', via: 'get'

  resources :users
  get "users/new"
  match '/signup',  to: 'users#new', via: 'get'
  match '/home', to: 'users#home', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resource :calendar, :only => [:show]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @user = current_user
    @course_ids = @user.courses_taken
    @courses = Course.all


    #  hiding courses taken
    if @course_ids != nil
      ##############
      @courses_taken = Course.find(@course_ids)
      @ordered_by = params[:order_by] if params.has_key? 'order_by'

      @course_taken_numbers = Array.new
      for course in @courses_taken
        @course_taken_numbers << course.course_number
      end
      # removing recitations and labs
      @courses = @courses.where.not(id: @course_ids)
      @to_be_removed = @courses.where(:course_number => @course_taken_numbers)
      @remove_ids = Array.new

      for course in @to_be_removed
         @remove_ids << course.id
      end
      ##############

      # hiding courses planning on taking #
      @user_events = Event.where(:user_id => @user.id)
      @course_event_ids = Array.new
      for events in @user_events
        @course_event_ids << events.course_id
      end

      if @course_event_ids.empty? or @course_event_ids == nil

      else
        @course_event_ids = @course_event_ids.compact
        @course_event_ids = @course_event_ids.uniq
      end

      # removing recitations and labs
      @course_plan = Course.find(@course_event_ids)
      @course_plan_numbers = Array.new
      for course in @course_plan
        @course_plan_numbers << course.course_number
      end
      @to_remove = @courses.where(:course_number => @course_plan_numbers)
      @remove_plan_ids = Array.new

      for course in @to_remove
        @remove_plan_ids << course.id
      end

      ###############

      # hiding courses
      @courses = @courses.where.not(id: [@course_ids, @remove_ids, @remove_plan_ids])

      # for ordering
      if @ordered_by
        @courses = @courses.all(:order => "#{@ordered_by} asc")
      else
        @courses
      end
    else
      @courses = Course.all
    end

  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # These two actions will behave like the standard edit and update actions 
  # but will handle multiple records. The selected_courses action will need a view.

  # In our application Courses is a RESTful resource so the two new actions won’t 
  # be accessible without making a change to our routes file. As we’re adding methods 
  # that will work on a collection of courses we’ll use the :collection option to 
  # add our two new actions.
  def selected_courses
    @courses = Course.find(params[:course_ids])
  end

  def select_courses_taken
    @hide_ids = Array.new
    @courses = Course.all
    @ordered_by = params[:order_by] if params.has_key? 'order_by'
    @to_be_hidden = @courses.where(:course_title => ["REC","Lab"])

    for course in @to_be_hidden
      @hide_ids << course.id
    end

    if @ordered_by
      @courses = @courses.where.not(id: @hide_ids)
      @courses = Course.all(:order => "#{@ordered_by} asc")
    else
      @courses = @courses.where.not(id: @hide_ids)
    end
  end

  def send_to_index
    if params[:course_taken_ids] != nil
      @courses = Course.find(params[:course_taken_ids])
      @add_to_user = Array.new
      for course in @courses
         @add_to_user << course.id
      end

      @user = current_user
      @user.courses_taken = @add_to_user
      @user.save!(validate:false)

      flash[:success] = "Success! You're ready to choose your classes for next semester"
      redirect_to url_for(:controller => 'users', :action => 'show', id: current_user.id)
    else
      flash[:success] = "Success! You're ready to choose your classes for next semester"
      redirect_to url_for(:controller => 'users', :action => 'show', id: current_user.id)
    end

  end


  def send_to_calendar

    @courses = Course.find(params[:course_ids])
    @start_time = Array.new
    @end_time = Array.new
    @title = Array.new
    @day = Array.new
    @instructor = Array.new
    @building = Array.new
    @room_number = Array.new
    @course_id = Array.new

    for course in @courses do
      @course_id << course.id

      if course.course_title != nil
        @title << course.course_title
      else
        @title << ' '
      end

      if course.start_time != nil
        @start_time << course.start_time
      else
        @start_time << ' '
      end

      if course.end_time != nil
        @end_time << course.end_time
      else
        @end_time << ' '
      end

      if course.day != nil
        @day << course.day
      end

      if course.instructor != nil
        @instructor << course.instructor
      else
        @instructor << 'TBA'
      end

      if course.building != nil
        @building << course.building
      else
        @building << 'TBA'
      end

      if course.room != nil
        @room_number << course.room
      else
        @room_number << 'TBA'
      end
    end

    require 'chronic'

    limit = @title.length
    limit.times do |count|
      @start = @start_time[count].strftime('%T')
      @end = @end_time[count].strftime('%T')

      @replace_start_m = Chronic.parse("this week monday at " + @start)
      @replace_end_m =  Chronic.parse("this week monday at " + @end)

      @replace_start_t = Chronic.parse("this week tuesday at " + @start)
      @replace_end_t =  Chronic.parse("this week tuesday at " + @end)

      @replace_start_w = Chronic.parse("this week wednesday at " + @start)
      @replace_end_w =  Chronic.parse("this week wednesday at " + @end)

      @replace_start_th = Chronic.parse("this week thursday at " + @start)
      @replace_end_th =  Chronic.parse("this week thursday at " + @end)

      @replace_start_f = Chronic.parse("this week friday at " + @start)
      @replace_end_f =  Chronic.parse("this week friday at " + @end)



      Time.zone = "UTC"
      Chronic.time_class = Time.zone

      if @day[count] == "M" #or 'T' or 'TH' or 'W' or 'F'
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_m, :ends_at => @replace_end_m, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "T"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_t, :ends_at => @replace_end_t, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "TH"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_th, :ends_at => @replace_end_th, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "W"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_w, :ends_at => @replace_end_w, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "F"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_f, :ends_at => @replace_end_f, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "M/W/F"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_m, :ends_at => @replace_end_m, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_w, :ends_at => @replace_end_w, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_f, :ends_at => @replace_end_f, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "M/W"
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_m, :ends_at => @replace_end_m, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save
        @event = current_user.events.build(:title => @title[count], :starts_at => @replace_start_w, :ends_at => @replace_end_w, :all_day => false, :description => "Instructor: " + @instructor[count] + "\n Building: " + @building[count] + "\n Room: " + @room_number[count] + "\n Days: " + @day[count], :course_id => @course_id[count])
        @event.save

      elsif @day[count] == "T/TH"

app/helpers/courses_helper.rb
module CoursesHelper
  def create_order_params(column)
    {order_by: column}
  end
end

app/views/courses/_course.html.erb
<li>
  <span class="content"><%= course.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(course.created_at) %> ago.
  </span>
</li>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_area %><br>
    <%= f.text_field :subject_area %>
  </div>
  <div class="field">
    <%= f.label :course_number %><br>
    <%= f.number_field :course_number %>
  </div>
  <div class="field">
    <%= f.label :ext_number %><br>
    <%= f.number_field :ext_number %>
  </div>
  <div class="field">
    <%= f.label :course_title %><br>
    <%= f.text_field :course_title %>
  </div>
  <div class="field">
    <%= f.label :instructor %><br>
    <%= f.text_field :instructor %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :building %><br>
    <%= f.text_field :building %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/edit_multiple.html.erb
<h3>Edit Selected Courses</h3>

<!-- At the top of this form we’ll put the opening form_tag. As the form isn’t going to be editing a particular course we’ll use a symbol rather than a variable that references a course. We’ll also need to specify a :url so that the form knows where to send its data and a :method so that PUT rather than POST is used. -->
<%= form_for :course, :url => update_multiple_courses_path, :html => {:method => :put} do |f| %>

<!-- In the form we’ll need to pass through the ids of the courses that were passed to it,or they will be lost when the form is submitted and we won’t know which courses to update. We can pass the ids as a series of hidden fields and, as we’re doing that, also show a list of the courses that are being updated to the user. -->
<ul>
  <% for course in @courses do %>
  <li>
    <%= hidden_field_tag "course_ids[]", course.id %>
    - <%= course.course_title %>
  </li>
  <%end%>
</ul>
<br/>

  <%= f.submit "Submit", :confirm => "Confirm the changes?" %>
  <%= link_to 'Cancel', courses_path, :method => :get ,
  :confirm => "Cancel all changes and go back to courses page?",
  :value => "Cancel"%>
<% end %>

app/views/courses/index.html.erb
<h1>Courses for Next Semester</h1>

<%= form_tag selected_courses_courses_path do %>
  <table class = "table table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th><%= link_to 'Subject Area', courses_path(create_order_params 'subject_area'), id: 'subject_area_header' %></th>
        <th><%= link_to 'Course Number', courses_path(create_order_params 'course_number'), id: 'course_number_header' %></th>
        <th><%= link_to 'Extension Number', courses_path(create_order_params 'ext_number'), id: 'ext_number_header' %></th>
        <th><%= link_to 'Course Title', courses_path(create_order_params 'course_title'), id: 'course_title' %></th>
        <th><%= link_to 'Instructor', courses_path(create_order_params 'instructor'), id: 'instructor_header' %></th>
        <th><%= link_to 'Day', courses_path(create_order_params 'day'), id: 'day_header' %></th>
        <th><%= link_to 'Start Time', courses_path(create_order_params 'start_time'), id: 'start_time_header' %></th>
        <th><%= link_to 'End Time', courses_path(create_order_params 'end_time'), id: 'end_time_header' %></th>
        <th><%= link_to 'Building', courses_path(create_order_params 'building'), id: 'building_header' %></th>
        <th><%= link_to 'Room', courses_path(create_order_params 'room'), id: 'room_header' %></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= check_box_tag "course_ids[]", course.id %></td>
          <td><%= course.subject_area %></td>
          <td><%= course.course_number %></td>
          <td><%= course.ext_number %></td>
          <td><%= course.course_title %></td>
          <td><%= course.instructor %></td>
          <td><%= course.day %></td>
          <td><%=if course.start_time != nil
                   course.start_time.localtime.strftime('%H:%M %Z')
                 end
          %></td>
          <td><%= if course.end_time != nil
                    course.end_time.localtime.strftime('%H:%M %Z')
                  end
          %></td>
          <td><%= course.building %></td>
          <td><%= course.room %></td>
          <td><%= link_to 'Show', course %></td>
          <!--<td><#%= link_to 'Edit', edit_course_path(course) %></td>-->
          <!--<td><#%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Review Checked", class: "btn btn-large btn-primary" %>
<% end %> 
<br>

<%= link_to 'New Course', new_course_path %>

<!-- jQuery library -->

<script type="text/javascript">
    $(function() {
        $(window).scroll(function() {
            if($(this).scrollTop() != 0) {
                $('#backtotop').fadeIn();
            }
        });

        $('#backtotop').click(function() {
            $('body,html').animate({scrollTop:0},800);
        });
    });
</script>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

<% form_for :dump, :url=>{:controller=>"courses", :action=>"csv_import"}, :html => { :multipart => true } do |f| -%>
    <table>
      <tr>
        <td>
          <label for="dump_file">
            Select a CSV File :
          </label>
        </td>
        <td >
          <%= f.file_field :file -%>
        </td>
      </tr>
      <tr>
        <td colspan='2'>
          <%= submit_tag 'Submit' -%>
        </td>
      </tr>
    </table>
<% end -%>

app/views/courses/select_courses_taken.html.erb
<h1>Select Courses Taken</h1>

<!-- At the top of this form we’ll put the opening form_tag. As the form isn’t going to be editing a particular course we’ll use a symbol rather than a variable that references a course. We’ll also need to specify a :url so that the form knows where to send its data and a :method so that PUT rather than POST is used. -->

<!-- In the form we’ll need to pass through the ids of the courses that were passed to it,or they will be lost when the form is submitted and we won’t know which courses to update. We can pass the ids as a series of hidden fields and, as we’re doing that, also show a list of the courses that are being updated to the user. -->
<%= form_tag send_to_index_courses_path do %>
    <table class = "table table-striped">
      <thead>
      <tr>
        <th></th>
        <th>Subject Area</th>
        <th>Course Number</th>
        <th>Course Title</th>
      </tr>
      </thead>

      <tbody>

      <% @courses.each do |course| %>
          <tr>
            <td><%= check_box_tag "course_taken_ids[]", course.id %></td>
            <td><%= course.subject_area %></td>
            <td><%= course.course_number %></td>
            <td><%= course.course_title %></td>
            <!--<td><#%= link_to 'Edit', edit_course_path(course) %></td>-->
            <!--<td><#%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>

    <%= submit_tag "Confirm", class: "btn btn-large btn-primary" %>
<% end %>
<br>

app/views/courses/selected_courses.html.erb
<h1>Your Selected Courses</h1>

<!-- At the top of this form we’ll put the opening form_tag. As the form isn’t going to be editing a particular course we’ll use a symbol rather than a variable that references a course. We’ll also need to specify a :url so that the form knows where to send its data and a :method so that PUT rather than POST is used. -->

<!-- In the form we’ll need to pass through the ids of the courses that were passed to it,or they will be lost when the form is submitted and we won’t know which courses to update. We can pass the ids as a series of hidden fields and, as we’re doing that, also show a list of the courses that are being updated to the user. -->
<%= form_tag send_to_calendar_courses_path do %>
    <table class = "table table-striped">
      <thead>
      <tr>
        <th></th>
        <th><%= link_to 'Subject Area', courses_path(create_order_params 'subject_area'), id: 'subject_area_header' %></th>
        <th><%= link_to 'Course Number', courses_path(create_order_params 'course_number'), id: 'course_number_header' %></th>
        <th><%= link_to 'Extension Number', courses_path(create_order_params 'ext_number'), id: 'ext_number_header' %></th>
        <th><%= link_to 'Course Title', courses_path(create_order_params 'course_title'), id: 'course_title' %></th>
        <th><%= link_to 'Instructor', courses_path(create_order_params 'instructor'), id: 'instructor_header' %></th>
        <th><%= link_to 'Day', courses_path(create_order_params 'day'), id: 'day_header' %></th>
        <th><%= link_to 'Start Time', courses_path(create_order_params 'start_time'), id: 'start_time_header' %></th>
        <th><%= link_to 'End Time', courses_path(create_order_params 'end_time'), id: 'end_time_header' %></th>
        <th><%= link_to 'Building', courses_path(create_order_params 'building'), id: 'building_header' %></th>
        <th><%= link_to 'Room', courses_path(create_order_params 'room'), id: 'room_header' %></th>
      </tr>
      </thead>

      <tbody>
      <% @courses.each do |course| %>
          <tr>
            <td><%= check_box_tag "course_ids[]", course.id, true %></td>
            <td><%= course.subject_area %></td>
            <td><%= course.course_number %></td>
            <td><%= course.ext_number %></td>
            <td><%= course.course_title %></td>
            <td><%= course.instructor %></td>
            <td><%= course.day %></td>
            <td><%=if course.start_time != nil
                     course.start_time.localtime.strftime('%H:%M %Z')
                   end
            %></td>
            <td><%= if course.end_time != nil
                      course.end_time.localtime.strftime('%H:%M %Z')
                    end
            %></td>
            <td><%= course.building %></td>
            <td><%= course.room %></td>
            <td><%= link_to 'Show', course %></td>
            <!--<td><#%= link_to 'Edit', edit_course_path(course) %></td>-->
            <!--<td><#%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>

    <%= submit_tag "Send to calendar", class: "btn btn-large btn-primary" %>
<% end %>
<br>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject Area:</strong>
  <%= @course.subject_area %>
</p>

<p>
  <strong>Course Number:</strong>
  <%= @course.course_number %>
</p>

<p>
  <strong>Extension Number:</strong>
  <%= @course.ext_number %>
</p>

<p>
  <strong>Course Title:</strong>
  <%= @course.course_title %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @course.instructor %>
</p>

<p>
  <strong>Day:</strong>
  <%= @course.day %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @course.start_time %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @course.end_time %>
</p>

<p>
  <strong>Building:</strong>
  <%= @course.building %>
</p>

<p>
  <strong>Room:</strong>
  <%= @course.room %>
</p>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/update_multiple.html.erb
<!-- At the top of this form we’ll put the opening form_tag. As the form isn’t going to be editing a particular course we’ll use a symbol rather than a variable that references a course. We’ll also need to specify a :url so that the form knows where to send its data and a :method so that PUT rather than POST is used. -->
<%= form_for :course, :url => selected_courses_courses_path, :html => { :method => :put } do |form| %>

<!-- In the form we’ll need to pass through the ids of the courses that were passed to it,or they will be lost when the form is submitted and we won’t know which courses to update. We can pass the ids as a series of hidden fields and, as we’re doing that, also show a list of the courses that are being updated to the user. -->
<ul>
  <% for course in @courses %>
  <li>
    <%= h course.course_title %>
    <%= hidden_field_tag "course_ids[]", course.id%>
  </li>
  <% end %>
</ul>

<!-- Next we’ll add the form elements for the attributes that a Courses has. There will be elements for the name, the category, the price, and for whether the course has been discontinued. When we submit this form we only want to update the fields that have had a value set against them, so for the fields that have a fixed number of options we’ll need to add a blank option so that the users can choose not update that field. -->


<ol class="formList">
<br/>
  	<li>
  		<%= collection_select(:course, :subject_area, Course.all, :id, :subject_area, :prompt => "---- Choose Subject ----")%>&nbsp;
	</li>
	<li>
		<%= collection_select(:course, :instructor, Course.all, :id, :instructor, :prompt => "---- Choose Instructor ----")%>&nbsp;
	</li>
	<li>
		<%= form.label :maximum_students, "Limit Number" %>
		<%= form.text_field :maximum_students%> &nbsp;
	</li>
	<li>
		<%= form.label :available, "Available" %>
	</li>
	<li>
		<%= form.select :available, [["Yes",1], ["No",0]], :include_blank => true  %>
  		<br/><br/>
	</li>
	<li>
		<%= form.label :course_title, "Course Title (disabled)" %>
	</li>
	<li>
		<%= form.text_field :course_title, :size => 26, :disabled => true%> &nbsp;
	</li>
<br/>

  <%= form.submit "Submit" %>

</ol>

<% end %>