config/routes.rb
MyCUplanner::Application.routes.draw do
  resources :events

  

  resources :courses do
    collection do
      post 'selected_courses'
      put 'update_multiple'
      post 'delete_multiple'
      post 'send_to_calendar'
      post 'send_to_index'
    end
  end

  match '/select_courses_taken', to: 'courses#select_courses_taken', via:'get'

  root :to => 'users#home'
  match '/about',   to: 'dynamic_pages#about',   via: 'get'
  match '/contact', to: 'dynamic_pages#contact', via: 'get'

  resources :users
  get "users/new"
  match '/signup',  to: 'users#new', via: 'get'
  match '/home', to: 'users#home', via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resource :calendar, :only => [:show]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Josh Fermin and Louis Bouddhou
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%= favicon_link_tag 'Logo - Interlocking CU (transparent background).ico' %>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">

    <div class="container">
      <% if signed_in? %>
        <%= link_to image_tag('myCUplannerLogo.png', size:"150x250", id: "logo"), controller: "users", action: "show", id: current_user.id %>
      <% else %>
        <%= link_to image_tag('myCUplannerLogo.png', size:"150x250", id: "logo"), root_path %>
      <% end %>
      <nav>
        <ul class="nav pull-right">

          <% if signed_in? %>
              <li><%= link_to "Profile", controller: "users", action: "show", id: current_user.id %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Planner <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Calendar", '/calendar' %></li>
                  <li><%= link_to "Schedule", '/events' %></li>
                </ul>
              </li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Courses <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Upcoming Courses", '/courses' %></li>
                  <li><%= link_to "Edit Courses Taken", '/select_courses_taken' %></li>
                </ul>
              </li>
          <% end %>
          <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Schedule", '/events' %></li>
                  <li><%= link_to "Courses", "/courses" %></li>
                  <li><%= link_to "About", root_path %></li>
                  <li><%= link_to "Edit Classes", '#' %></li>

                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
                  <li><%= link_to "Sign Up", signup_path %></li>
                  <li><%= link_to "Log In", signin_path %></li>
              </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>